#### Basics of numpy
Learning from this tutorial - http://cs231n.github.io/python-numpy-tutorial/

In [2]:
import numpy as np

#### Shape of numpy arrays

In [3]:
a = np.array([1, 2, 3])
print a.shape

(3,)


In [4]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print b.shape

(3, 4)


#### Indexing by integers and slices

The result of indexing by slices is always a subarray of the original.

The result of indexing by integers can be used to construct arbitrary arrays.

In [5]:
# extract using slices
# 1: -> all rows >= 1
# 1:3 -> all columns [1,3) i.e. 1 and 2
print b[1:, 1:3]

[[ 6  7]
 [10 11]]


In [6]:
# 1:3 -> all rows between 1 and 3
# 2:3 -> all columns [2,3) i.e. 2.
print b[1:3, 2:3]

[[ 7]
 [11]]


In [7]:
# extract single row using integers
# 1 -> row 1
# : -> all columns
# The result is a single array.
c = b[1, :]
print c.shape

(4,)


In [8]:
# extract single row using slices - the difference between this and the above method using an integer
# is the shape of the result.
# 1:2 -> row 1
# The number of columns is the same as the original (b)
d = b[1:2, :]
print d.shape

(1, 4)


In [9]:
# Similarly for columns
# This results in a single array.
# : -> all rows
# 2 -> column 2
e = b[:, 2]
print e.shape

(3,)


In [10]:
# This results in an array with the same number of rows as the original.
# : -> all rows
# 2:3 -> all columns [2:3) i.e. 2.
f = b[:, 2:3]
print f.shape

(3, 1)


In [11]:
a = np.array([[1,2], [3,4], [5,6]])
print a.shape
# get all rows
print a[[0,1,2]]
# get col 0 of row 0, col 1 of row 1, col 0 of row 2
print a[[0,1,2],[0,1,0]]
# print the same element (col 1 of row 0) from a
print a[[0, 0], [1, 1]]

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[2 2]


#### Mutating using integer indexes

In [12]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
# get cols 0, 2, 1 of rows 0,1,2 respectively
print a[np.arange(3), np.array([0,2,1])]

# get a[0,2] and a[1,1] 
print a[np.arange(2), np.array([2,1])]

# increment a[0,2] and a[1,1] by 10
a[np.arange(2), np.array([2, 1])] += 10
print a

[ 1  7 10]
[3 6]
[[ 1  2 13  4]
 [ 5 16  7  8]
 [ 9 10 11 12]]


#### Using boolean indexes

In [13]:
a = np.array([[1,2], [3,4], [5,6]])

# get all elements > 2
ind = (a > 2)
print a[ind]
print a[a>2]

[3 4 5 6]
[3 4 5 6]


#### Array and matrix math

In [14]:
# Element-wise operations
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[7, 8], [9, 10]], dtype=np.float64)

print x + y # same as np.add(x, y)

print x - y # same as np.subtract(x, y)

# element-wise multiplication NOT matrix multiplication
print x * y # same as np.multiply(x, y)

print x / y # same as np.divide(x, y)

[[ 8. 10.]
 [12. 14.]]
[[-6. -6.]
 [-6. -6.]]
[[ 7. 16.]
 [27. 40.]]
[[0.14285714 0.25      ]
 [0.33333333 0.4       ]]


In [15]:
# Vectors
v = np.array([13, 14])
w = np.array([15, 16])
print v.shape

print v.dot(w) # results in a scalar

# product of matrix and vector
print x.dot(v) # same as np.dot(x, v) 

# product of 2 matrices
print x.dot(y) 

(2,)
419
[41. 95.]
[[25. 28.]
 [57. 64.]]


#### Broadcasting 

Broadcasting is how numpy treats arrays of different sizes during arithmetic operations. 

In [16]:
# simple example of broadcasting to add a scalar to a vector. 
# numpy treats y as if it were an array with dim (3,1)
x = np.array([1,2,3])
y = 2
print x + y

array([3, 4, 5])

In [28]:
# For broadcasting, arrays have to have compatible shapes. 
# The dimensions have to be equal or one of them has to be 1.
x = np.array([[[1, 2, 3],
               [4, 5, 6]],
              [[7, 8, 9],
              [10, 11, 12]],
             [[13, 14, 15],
             [16, 17, 18]]])
print x.shape
y = np.array([[10, 20, 30],
              [40, 50, 60]])
print y.shape
print x * y

z = np.array([[10, 20, 30]])
print z.shape

print x * z

(3, 2, 3)
(2, 3)
[[[  10   40   90]
  [ 160  250  360]]

 [[  70  160  270]
  [ 400  550  720]]

 [[ 130  280  450]
  [ 640  850 1080]]]
(1, 3)
[[[ 10  40  90]
  [ 40 100 180]]

 [[ 70 160 270]
  [100 220 360]]

 [[130 280 450]
  [160 340 540]]]
(3,)
(3, 3)
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [35]:
v = np.array([1, 2, 3])
w = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print v.shape
print w.shape

# add a vector to each row of a matrix
print v + w

# add a vector to each column of a matrix
print v.reshape(3, 1) + w

(3,)
(3, 3)
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [26]:
# examples where broadcasting doesn't work
x = np.array([1, 2, 3])
y = np.array([10, 20])

print x + y

ValueError: operands could not be broadcast together with shapes (3,) (2,) 